-- Active: 1682668039818@@127.0.0.1@3306
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS mezmur;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE mezmur (
  m_id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  titleen TEXT,
  azmach TEXT NOT NULL,
  azmachen TEXT,
  dir TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE mezmurtable (
  m_id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  titleen TEXT,
  azmach TEXT NOT NULL,
  azmachen TEXT,
  cat1 TEXT NOT NULL,
  cat2 TEXT NOT NULL,
  cat3 TEXT NOT NULL,
  dir TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  
);