-- Active: 1682668039818@@127.0.0.1@3306
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS mezmur;
DROP TABLE IF EXISTS mezmur_org1;
DROP Table IF EXISTS tags;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE mezmur_org1 (
  m_id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  titleen TEXT,
  azmach TEXT NOT NULL,
  azmachen TEXT,
  dir TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE mezmur (
  m_id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  titleen TEXT,
  azmach TEXT NOT NULL,
  azmachen TEXT,
  dir TEXT NOT NULL,
  audio_file TEXT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  cat1 TEXT NOT NULL,
  cat2 TEXT NOT NULL,
  cat3 TEXT NOT NULL
);

CREATE TABLE tagList (
  t_id INTEGER PRIMARY KEY,
  tag TEXT NOT NULL UNIQUE
);

CREATE TABLE mezTags (
  tag_id INTEGER,
  m_id INTEGER,
  tag TEXT NOT NULL,
  FOREIGN KEY (m_id) REFERENCES mezmur(m_id)
  FOREIGN KEY (tag_id) REFERENCES tagList(t_id)
  PRIMARY KEY (m_id, tag_id)
);
